---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.blade.php"
  - "**.php"
exclude_paths:
- tests/
